using System.Collections.Generic;
using System.Text.Json.Serialization;
using Core.Entities.AuditableEntity;

namespace Core.Entities
{
   public class EnumData : IAuditableEntity
   {
      public EnumData()
      {
         Children = new HashSet<EnumData>();
      }

      public int Id { get; set; }
      public int? ParentId { get; set; }
      public SystemTypes SystemType { get; set; }
      public string Title { get; set; }
      public string Data { get; set; }
      public string Category { get; set; }
      public int? SortKey { get; set; }
      public virtual EnumData Parent { get; set; }
      public virtual ICollection<EnumData> Children { get; set; }
      public virtual ProductClassification ProductClassification { get; set; }
   }

   public enum SystemTypes : int
   {
      IsicCode2 = 0,
      IsicCode4 = 1,
      //   IndustryClassification = 2,
      IndustryLicense = 3,
      MeasurementUnit = 4,
      Province = 5,
      State = 6,
      City = 7,
      HsCode = 8,
      BaselAb = 9,
      BaselY = 10,
      BaselH = 11,
      WasteClassification = 12,
      Waste = 13,
      IngredientsClassification = 14,
      Ingredient = 15,
      WasteManagementMethod = 16,
      BaselRd = 17,
      IsicCode10 = 18,
      // WasteDisposalLocation,
      FuelType = 19,
      MonitoringType = 20,
      PollutionReleaseSource = 21,
      SpecialtySection = 22,
      DeviceType = 23,
      WastewaterType = 24,
      WastewaterPurificationSystemType = 25,
      WastewaterProductionReleaseType = 26,
      WastewaterCombinationClassification = 27,
      DangerousProperties = 28,
      SubmissionMethod = 29,
      WasteManagementUnitType = 30,
      Major = 31,
      Grade = 32,
      Rank = 33,
      BaseRanking = 34,
      UsageLocations = 35,
      ForeignLanguage = 36,
      IndustryReferralTimeActivityMethod = 37,
      ApplicantStatus = 38,
      OwnershipStatus = 39,
      Bank = 40,
      AcceptedResources = 41,
      HunterWeaponLicenseIssuer = 42,
      Countries = 43,
      CalibrationPeriod = 44,
      ConsumableMaterialStandardClassification = 45,
      SlaughterHouseClassification = 46,
      LandType = 47,
      MedicalCenterActivityType = 48,
      MedicalCenterDependencyType = 49,
      WasteEstimateWay = 50,
      DisinfectionDeviceStatus = 51,
      DeviceInActivityCause = 52,
      DisinfectionDeviceOwnership = 53,
      AlternativeDisinfectionMethod = 54,
      DisinfectionMethod = 55,
      MedicalWastesReceivers = 56,
      MedicalWastesDisposalMethod = 57,
      MunicipalityCompanyReceivedTariff = 58,
      WasteHoldingMethod = 59,
      EstablishmentGrouping = 60,
      LivestockClassification = 61,
      DomesticatedAnimalsClassification = 62,
      MonitoringPeriod = 63,
      EstablishmentGroupingClassification = 64,
      MaintainableMaterialClassification = 65,
      DepotLocationType = 66,
      NormalWasteTransportFrequency = 67,
      OperationalProcess = 68,
      StationDataSendingFrequency = 69,
      StationType = 70,
      StationUsageClassification = 71,
      StationModel = 72,
      StationMeteorologicalSystem = 73,
      StationSpareParts = 74,
      StationConsumables = 75,
      AirQualityMonitoringStationParameters = 76,
      SatisfactionLevel = 77,
      TemplateKeyword = 78,
      WasteProduceFrequency = 79,
      ProducedWasteLocation = 80,
      FlareType = 81,
      SendingGasType = 82,
      InspectReason = 83,
      Season = 84,
      GeneralAdministrationOpinion = 85,
      MonitoringTypeQualityStatus = 86,
      Indicator = 87,
      Criterion = 88,
      UnderCriteria = 89,
      Strategy = 90,
      WateringSystemType = 91,
      SpeciesVegetationType = 92,
      LicenseType = 93,
      WasteTransferPeriod = 94,
      GreenIndustryLimitations = 95,
      MainBasin = 96,
      SecondaryBasin = 97,
      RiverUsageType = 98,
      RiverRange = 99, //StudyArea
      HydrometryStationType = 100,
      HydrometryEquipmentType = 101,
      GraphType = 102,
      DataLoggerCompany = 103,
      HydrometryBuilderCompany = 104,
      StationMonitoringFrequency = 105,
      StationMonitoringParameter = 106,
      WaterQualityStationType = 107,
      WaterOnlineQualityMonitoringStationType = 108,
      WaterOnlineQualityMonitoringStationUsageClassification = 109,
      WaterOnlineQualityMonitoringStationModel = 110,
      WaterOnlineQualityMonitoringStationSpareParts = 111,
      WaterOnlineQualityMonitoringStationConsumables = 112,
      WaterOnlineQualityMonitoringStationParameters = 113,
      HuntingType = 114,
      AnimalType = 115,
      DayInWeek = 116,
      // ProvinceRegion = 117,
      Religion = 118,
      HunterWeaponType = 119,
      HunterWeaponModel = 120,
      FishermanToolsType = 121,
      FishermanToolsModel = 122,
      HunterViolationType = 123,
      HunterViolationDegree = 124,
      HunterRuleStatus = 125,
      HunterDeprivationType = 126,
      Species = 127,
      Subspecies = 128,
      HunterDeviceType = 129,
      HospitalMonitoringPeriod = 130,
      // DisinfectionDeviceType = 131,
      GuidanceMonitoringCondition = 132,
      DisinfectionDeviceShredderType = 133,
      StationUpstairsFacilityAndStructure = 134,
      Deputy = 135,
      Office = 136,
      OfficeGroup = 137,
      AssistanceClassification = 138,
      IndustryClosureReason = 139,
      WaterStationSamplingReason = 140,
      WaterYear = 141,
      AirAppearance = 142,
      FlowAppearance = 143,
      StationMonitoringParameterClassification = 144,
      PermittedExportWaste = 145,
      PermittedImportWaste = 146,
      WastePackagingType = 147,
      ConventionChemicalAttachment = 148,
      ConventionChemicalGroup = 149,
      MineType = 150,
      MineralGroup = 151,
      MineralMaterial = 152,
      WasteDamType = 153,
      SoilType = 154,
      BurialMethod = 155,
      TicketType = 156,
      KnowledgeGroup = 157,
      IndustryEstablishmentDocumentType = 158,
      WasteMaterialMode = 159,
      WasteKeepingMethod = 160,
      WasteCollectMethod = 161,
      RoadType = 162,
      LandUsage = 163,
      DistanceFromCentersAreasEcosystems = 164,
      QuadrupleAreaType = 165,
      QuadrupleArea = 166,
      HerbalPhyllum = 167,
      HerbalClass = 168,
      HerbalOrder = 169,
      HerbalFamily = 170,
      HerbalGenus = 171,
      HerbalSpecies = 172,
      HerbalSubSpecies = 173,
      HerbalVariety = 174,
      HerbalType = 175,
      HerbalProtectedZone = 176,
      HerbalEcosystem = 177,
      HerbalTopography = 178,
      HerbalSoilType = 179,
      HerbalLifeForm = 180,
      HerbalChoroType = 181,
      HerbalConservationStatus = 182,
      AnimalKingdom = 183,
      AnimalPhylum = 184,
      AnimalClass = 185,
      AnimalOrder = 186,
      AnimalFamily = 187,
      AnimalGenus = 188,
      AnimalSpecies = 189,
      AnimalSubSpecies = 190,
      AnimalMuseumType = 191,
      AnimalProtectedZone = 192,
      AnimalEcosystem = 193,
      AnimalPreservation = 194,
      AnimalConservationStatus = 195,
      GeneticsKingdom = 196,
      GeneticsPhylum = 197,
      GeneticsClass = 198,
      GeneticsOrder = 199,
      GeneticsFamily = 200,
      GeneticsGenus = 201,
      GeneticsSpecies = 202,
      GeneticsSubSpecies = 203,
      GeneticsVariety = 204,
      GeneticsType = 205,
      GeneticsProtectedZone = 206,
      GeneticsSpecimenType = 207,
      GeneticsQuality = 208,
      GeneticsConservationStatus = 209,
      AncientKingdom = 210,
      AncientPhylum = 211,
      AncientClass = 212,
      AncientOrder = 213,
      AncientFamily = 214,
      AncientSubFamily = 215,
      AncientGenus = 216,
      AncientSpecies = 217,
      AncientType = 218,
      AncientProtectedZone = 219,
      MineralStoneMineralType = 220,
      MineralStoneStoneType = 221,
      MineralStoneHardness = 222,
      MineralStoneCrystallizationSystem = 223,
      MineralStoneProtectedZone = 224,
      HerbalKingdom = 225,
      Accuracy = 226,
      HerbalLocation = 227,
      AnimalLocation = 228,
      GeneticsLocation = 229,
      AncientLocation = 230,
      MineralStoneLocation = 231,
      IndustryEstablishmentInspectionStage = 232,
      AncientAge = 233,
      JudicialCaseStatus = 234,
      JudicialVerdict = 235,
      PlainType = 236,
      AltitudeType = 237,
      AqueductType = 238,
      AqueductWaterSourceStabilityType = 239,
      PitType = 240,
      PitWaterSourceStabilityType = 241,
      FountainType = 242,
      FountainWaterSourceStabilityType = 243,
      IndustrialActivitiesClassification = 244,
      MammalsSpecie = 245,
      BirdsGenus = 246,
      BirdsSpecie = 247,
      IndustryEstablishmentInquiryType = 248
   }
}
